name: Publish runpod-comfy-worker image

on:
  push:
    branches:
      - master
    paths:
      - 'runpod-comfy-worker/**'
      - '!runpod-comfy-worker/docs/**'
      - '!runpod-comfy-worker/README.md'

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pre-cleanup disk
        run: |
          echo "Disk before cleanup:"
          df -h
          rm -rf ~/.cache/pip || true
          sudo rm -rf /opt/hostedtoolcache || true
          sudo rm -rf /usr/share/miniconda || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /usr/local/lib/android || true
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/* || true
          docker system prune -af || true
          docker builder prune -af || true
          echo "Disk after cleanup:"
          df -h

      - name: Build and push using Bake
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl
          targets: worker
          push: true
          no-cache: true
